# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5c4cf9b5a28cb9a3da381d38b07e75f1ac7ac616efa48b2422f529e3ae1878bfadb3d530e7a3cbe3dc0b51d32ea855ca55a97df9ca623c8beeab4504b7533be

test:
  secret_key_base: b49a704ba6f590764b30b6c117407fd23cde74a786f58092e7d6ae5b07f9e3ffa053e7b5f2d31ed2a52956799a9b7eb3a163695a97b96a0a0b2c842fc072571d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
